### REGISTER
POST http://localhost:3001/api/v1/access/register
Content-Type: application/json

{
    "roles": [
        {
            "role": {
                "name": "Teacher",
                "privileges": [{ "action": "view-student", "relationship": "teaches" }]
            },
            "child": [{
                "role": {
                    "name": "Executive",
                    "privileges": [{ "action": "view-school", "relationship": "established" }]
                },
                "child": []
            }]
        },
        {
            "role": {
                "name": "Parent",
                "privileges": [{ "action": "view-student", "relationship": "parent-of" }]
            },
            "child": []
        },
        {
            "role": {
                "name": "Student",
                "privileges": [{ "action": "view-student", "relationship": "own" }]
            },
            "child": []
        }
    ]
}

### AUTHORIZE
POST http://localhost:3001/api/v1/access/authorize
Content-Type: application/json

{
    "fromId": "6777687824ab2afd5c9a71e8",
    "fromRoleIds": ["67793141d093f9a0418633d7"],
    "toId": "6777687824ab2afd5c9a71e7",
    "action": "Application: manage-users"
}