### BIND
POST http://localhost:3001/api/v1/relationships/bind
Content-Type: application/json

{
    "initiators": [
        { "entityId": "6766a7b0f98d0442e37d8315", "relationship": "manages" }
    ],
    "targetId": "6766a7b0f98d0442e37d8310",
    "conditions": [
        { "fromRel": "manages", "toRel": "studies_at", "resultRel": "teaches" },
        { "fromRel": "manages", "toRel": "employed_at", "resultRel": "supervises_teachers" },
        { "fromRel": "manages", "toRel": "associated_with", "resultRel": "supervises_parents" }
    ]
}

### UNBIND
DELETE http://localhost:3001/api/v1/relationships/unbind
Content-Type: application/json

{
    "terminators": [
        { "entityId": "6766a7b0f98d0442e37d8315", "relationship": "manages" }
    ],
    "targetId": "6766a7b0f98d0442e37d8310",
    "conditions": [
        { "fromRel": "manages", "toRel": "studies_at", "resultRel": "teaches" },
        { "fromRel": "manages", "toRel": "employed_at", "resultRel": "supervises_teachers" },
        { "fromRel": "manages", "toRel": "associated_with", "resultRel": "supervises_parents" }
    ]
}

### GET BY ID
GET http://localhost:3001/api/v1/relationships/6778e8f67bb97d902f46d85c

### GET BY FROM
GET http://localhost:3001/api/v1/relationships/from/67b1b74f8761094060981f37

### GET BY TO
GET http://localhost:3001/api/v1/relationships/to/67b1b74f8761094060981f37

### INSERT
POST http://localhost:3001/api/v1/relationships
Content-Type: application/json

{
    "from": "6777687824ab2afd5c9a71e8",
    "to": "6777687824ab2afd5c9a71e7",
    "relationship": "Application: manage-users"
}

### UPDATE
PATCH http://localhost:3001/api/v1/relationships/6778e8f67bb97d902f46d85c
Content-Type: application/json

{
    "relationship": "manage"
}

### DELETE BY ID
DELETE http://localhost:3001/api/v1/relationships/6778e8f67bb97d902f46d85c


### DELETE BY FROM
DELETE http://localhost:3001/api/v1/relationships/from/6777687824ab2afd5c9a71e8


### DELETE BY TO
DELETE http://localhost:3001/api/v1/relationships/to/6777687824ab2afd5c9a71e6

### DELETE BY FROM TO IDS
DELETE http://localhost:3001/api/v1/relationships
Content-Type: application/json

{
    "ids": ["6778e8f67bb97d902f46d85c", "6778e8f67bb97d902f46d85d"]
}

### DELETE BY FROM TO RELATIONSHIP
DELETE http://localhost:3001/api/v1/relationships/by-from-to-rel
Content-Type: application/json

{
    "from": "67b198b7e37bbd4d7ef2dcc0",
    "to": "67a3a1aa33d93aaeeb1c84a3",
    "relationship": "parent-of"
}