### BIND
POST http://localhost:3001/api/v1/relationships/bind
Content-Type: application/json

{
    "initiators": [
        { "entityId": "6766a7b0f98d0442e37d8315", "relationship": "MANAGES" }
    ],
    "targetId": "6766a7b0f98d0442e37d8310",
    "conditions": [
        { "fromRel": "MANAGES", "toRel": "STUDIES_AT", "resultRel": "TEACHES" },
        { "fromRel": "MANAGES", "toRel": "EMPLOYED_AT", "resultRel": "SUPERVISES_TEACHERS" },
        { "fromRel": "MANAGES", "toRel": "ASSOCIATED_WITH", "resultRel": "SUPERVISES_PARENTS" }
    ]
}

### UNBIND
DELETE http://localhost:3001/api/v1/relationships/unbind
Content-Type: application/json

{
    "terminators": [
        { "entityId": "6766a7b0f98d0442e37d8315", "relationship": "MANAGES" }
    ],
    "targetId": "6766a7b0f98d0442e37d8310",
    "conditions": [
        { "fromRel": "MANAGES", "toRel": "STUDIES_AT", "resultRel": "TEACHES" },
        { "fromRel": "MANAGES", "toRel": "EMPLOYED_AT", "resultRel": "SUPERVISES_TEACHERS" },
        { "fromRel": "MANAGES", "toRel": "ASSOCIATED_WITH", "resultRel": "SUPERVISES_PARENTS" }
    ]
}

### GET BY ID
GET http://localhost:3001/api/v1/relationships/6778e8f67bb97d902f46d85c

### GET BY FROM
GET http://localhost:3001/api/v1/relationships/from/6777687824ab2afd5c9a71e8

### GET BY TO
GET http://localhost:3001/api/v1/relationships/to/6777687824ab2afd5c9a71e7

### INSERT
POST http://localhost:3001/api/v1/relationships
Content-Type: application/json

{
    "from": "6777687824ab2afd5c9a71e8",
    "to": "6777687824ab2afd5c9a71e7",
    "relationship": "Application: manage-users"
}

### UPDATE
PATCH http://localhost:3001/api/v1/relationships/6778e8f67bb97d902f46d85c
Content-Type: application/json

{
    "relationship": "manage"
}

### DELETE BY ID
DELETE http://localhost:3001/api/v1/relationships/6778e8f67bb97d902f46d85c


### DELETE BY FROM
DELETE http://localhost:3001/api/v1/relationships/from/6777687824ab2afd5c9a71e8


### DELETE BY TO
DELETE http://localhost:3001/api/v1/relationships/to/6777687824ab2afd5c9a71e6

### DELETE BY FROM TO IDS
DELETE http://localhost:3001/api/v1/relationships
Content-Type: application/json

{
    "ids": ["6778e8f67bb97d902f46d85c", "6778e8f67bb97d902f46d85d"]
}