### GET (ADMIN)
GET http://localhost:3001/api/v1/roles

### GET WITH FILTER (ADMIN) (searchTerm)
GET http://localhost:3001/api/v1/roles?searchTerm=en

### GET BY ID (ADMIN)
GET http://localhost:3001/api/v1/roles/67777ae3f4371ef110d7e892

### INSERT (ADMIN)
POST http://localhost:3001/api/v1/roles
Content-Type: application/json

{
    "name": "test1",
    "isLocked": false,
    "privileges": {
        "mandatory": [],
        "optional": []
    },
    "parents": {
        "mandatory": [],
        "optional": []
    }
}


### UPDATE (ADMIN)
PATCH http://localhost:3001/api/v1/roles/67777ae3f4371ef110d7e892
Content-Type: application/json

{
    "optionalParents": ["67779a9887c5499457d6a2f4"]
}

### DELETE (ADMIN)
DELETE http://localhost:3001/api/v1/roles/67779a9887c5499457d6a2f4